# .github/FUNDING.yml
# Controls the Sponsor button shown on the GitHub repository page.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Credit card donations via GitHub Sponsors
github: lchonkan

